### ISSUE TITLE
Copying text to clipboard

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix-ui-samples-2#20]
For example like in https://github.com/jmix-framework/jmix-ui-samples-2/blob/669f3f92700dc075c7dc80c08093a4c58933f862/src/main/java/io/jmix/uisamples/view/sys/sampleview/SampleView.java#L378

**Comment by KremnevDmitry** [comment]
Online now: https://demo.jmix.io/ui-samples/sample/copy-to-clipboard
